language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: appgames
  api_key:
    secure: dBFb1QM0odT08MLQHb0CBDGXPa3n+ZFkHBMEKTRVOwek+eXwzTlcO8JBlDSlpYj77GcNVPmL4EBZM3kkQEu7muKpGMQAlZkBOhT66JGkZuq1+pTIm+v+07D16aMhOr2s5W3fu7fEivXwIUaOdgqqdY+F2/vDE/PN+XK9l7mRPX1x5sIvlHLmug/BF73nSKV+NCSYX71XSHLFJKVis9TSZ0BM5EfMw8d5tGRd2CcivRfRO5Gd5mYwEFk+ispIuAfLju1cxkyHNu/AESlYrJWdByb3HSpjcIdwXvmEHonOYTX2qKMuUbulHCDANpbJ42TbECK/93rTHAgznV2b5o75bYRgBPP+jIw7Ki/y+HAEb236YpMBxnj+Kv6CgmNGvdIzPrsvUjz58HHhPjoQ56KfWG4v81GHGq9CAKQfu7irn55jClFEtyurTNUQuNQVnv0veJyLwMXS0wH+GUcc573tWKdqskyAW66RjFUj8OXqct7Yewjecwg33OwqDg9eBVN0nShlI66LrPg9UDSR7o4N3lNICGzIEJN7ZrkVNh/KpE8/WHmP7amvepIAaqupnRYErpTYcTgERGDa0FyNVxO1JbHfapcQRoPAEOJgj5fS0LE7GZ490t64VDrkgmdD1aB2cAKf7Zk1xOA5aYOWWp+ORrJTYWrgzlMjYpbixrFmyM8=
